-- MySQL Script generated by MySQL Workbench
-- Fri Jan 12 16:27:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBOpenFoodFacts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBOpenFoodFacts` DEFAULT CHARACTER SET utf8 ;
USE `DBOpenFoodFacts` ;

-- -----------------------------------------------------
-- Table `DBOpenFoodFacts`.`BD_OFF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOpenFoodFacts`.`BD_OFF` (
  `OFF_id` INT NOT NULL AUTO_INCREMENT,
  `OFF_name` VARCHAR(45) NOT NULL,
  `OFF_url` VARCHAR(150) NOT NULL,
  `OFF_product` INT NOT NULL,
  PRIMARY KEY (`OFF_id`, `OFF_product`),
  UNIQUE INDEX `OFF_product_UNIQUE` (`OFF_product` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBOpenFoodFacts`.`BD_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOpenFoodFacts`.`BD_User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `User_name` VARCHAR(45) NOT NULL,
  `User_product_FK` INT NOT NULL,
  PRIMARY KEY (`User_id`, `User_product_FK`),
  INDEX `fk_BD_User_BD_OFF_idx` (`User_product_FK` ASC),
  CONSTRAINT `fk_BD_User_BD_OFF`
    FOREIGN KEY (`User_product_FK`)
    REFERENCES `DBOpenFoodFacts`.`BD_OFF` (`OFF_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
