-- MySQL Script generated by MySQL Workbench
-- Tue Jan 23 02:36:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBOpenFoodFacts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBOpenFoodFacts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBOpenFoodFacts` DEFAULT CHARACTER SET utf8 ;
USE `DBOpenFoodFacts` ;

-- -----------------------------------------------------
-- Table `DBOpenFoodFacts`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOpenFoodFacts`.`Categories` (
  `cat_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(75) NOT NULL,
  `cat_url` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBOpenFoodFacts`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOpenFoodFacts`.`User` (
  `User_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `User_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBOpenFoodFacts`.`Saved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOpenFoodFacts`.`Saved` (
  `sav_id` INT UNSIGNED NOT NULL,
  `sav_name` VARCHAR(75) NOT NULL,
  `sav_cat_id` INT UNSIGNED NOT NULL COMMENT 'Description',
  `sav_shop` VARCHAR(75) NULL,
  `sav_url` VARCHAR(150) NOT NULL,
  `sav_user_id` INT UNSIGNED NOT NULL,
  INDEX `fk_sav_user_id_idx` (`sav_user_id` ASC),
  INDEX `fk_sav_cat_id_idx` (`sav_cat_id` ASC),
  PRIMARY KEY (`sav_id`),
  CONSTRAINT `fk_sav_user_id`
    FOREIGN KEY (`sav_user_id`)
    REFERENCES `DBOpenFoodFacts`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sav_cat_id`
    FOREIGN KEY (`sav_cat_id`)
    REFERENCES `DBOpenFoodFacts`.`Categories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
